version: '3.4'

services:
  vc-db:
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "${DOCKER_SQL_PORT:-1433}:1433"
    expose:  
      - 1433  
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=v!rto_Labs!
    volumes:
      - db-volume:/var/opt/mssql   
    networks:
      - virto

  virtocommerce.platform.web:
    ports:
      - "${DOCKER_PLATFORM_PORT:-8090}:80"
    environment:
     - VirtoCommerce:AllowInsecureHttp=true
     - ConnectionStrings__VirtoCommerce=Data Source=vc-db;Initial Catalog=VirtoCommerce3docker;Persist Security Info=True;User ID=sa;Password=v!rto_Labs!;MultipleActiveResultSets=False;
     - Assets__FileSystem__PublicUrl=http://localhost:${DOCKER_PLATFORM_PORT:-8090}/assets/
     - Content__FileSystem__PublicUrl=http://localhost:${DOCKER_PLATFORM_PORT:-8090}/cms-content/
    depends_on:
      - vc-db
    entrypoint: ["vc-db:1433", "-t", "120", "--", "dotnet", "VirtoCommerce.Platform.Web.dll"]
    networks:
      - virto

volumes:
  db-volume:
    name: db-volume

networks:
  virto:
     external:
        name: nat
