# v3.800.23
# https://virtocommerce.atlassian.net/browse/VCST-3056
name: Release

on:
  workflow_dispatch:

jobs:
  release:
    uses: VirtoCommerce/.github/.github/workflows/release.yml@v3.800.23    
    secrets:
      envPAT: ${{ secrets.REPO_TOKEN }}