# v3.800.4
# https://virtocommerce.atlassian.net/browse/VCST-488
name: Release

on:
  workflow_dispatch:

jobs:
  release:
    uses: VirtoCommerce/.github/.github/workflows/release.yml@v3.800.4
    secrets:
      envPAT: ${{ secrets.REPO_TOKEN }}