# v3.800.19
# https://virtocommerce.atlassian.net/browse/VCST-923
name: Release

on:
  workflow_dispatch:

jobs:
  release:
    uses: VirtoCommerce/.github/.github/workflows/release.yml@v3.800.19    
    secrets:
      envPAT: ${{ secrets.REPO_TOKEN }}